export const CREATE_COLLECTION_TO_DO = 'CREATE_COLLECTION_TO_DO';

export const CREATE_TO_DO_LIST = 'CREATE_TO_DO_LIST';

export const CHANGE_COMPLETE_STATE = 'CHANGE_COMPLETE_STATE';

export const MAKE_COLLECTION_TO_DO_ACTIVE = 'MAKE_COLLECTION_TO_DO_ACTIVE';

export const SHOW_MODAL_SUCCESSFUL_OPERATION = 'SHOW_MODAL_SUCCESSFUL_OPERATION';

export const HIDE_MODAL_SUCCESSFUL_OPERATION = 'HIDE_MODAL_SUCCESSFUL_OPERATION';

export const SHOW_MODAL_SUCCESSFUL_OPERATION_LEFT_LIST = 'SHOW_MODAL_SUCCESSFUL_OPERATION_LEFT_LIST';

export const SHOW_MODAL_SUCCESSFUL_OPERATION_RIGHT_LIST = 'SHOW_MODAL_SUCCESSFUL_OPERATION_RIGHT_LIST';

