export const CREATE_COLLECTION_TO_DO = 'CREATE_COLLECTION_TO_DO';

export const CREATE_TO_DO_LIST = 'CREATE_TO_DO_LIST';

export const CHANGE_COMPLETE_STATE = 'CHANGE_COMPLETE_STATE';

export const MAKE_COLLECTION_TO_DO_ACTIVE = 'MAKE_COLLECTION_TO_DO_ACTIVE';

export const SHOW_MODAL_SUCCESSFUL_OPERATION = 'SHOW_MODAL_SUCCESSFUL_OPERATION';

export const HIDE_MODAL_SUCCESSFUL_OPERATION = 'HIDE_MODAL_SUCCESSFUL_OPERATION';

export const SHOW_MODAL_REMOVE_LIST_ITEM = 'SHOW_MODAL_REMOVE_LIST_ITEM';

export const HIDE_MODAL_REMOVE_LIST_ITEM = 'HIDE_MODAL_REMOVE_LIST_ITEM';

export const REMOVE_LIST_ITEM = 'REMOVE_LIST_ITEM';

export const REMOVE_LIST_ITEM_WHEN_DELETING_A_SHEET = 'REMOVE_LIST_ITEM_WHEN_DELETING_A_SHEET';

export const REMOVE_LIST = 'REMOVE_LIST';

export const REMOVE_LIST_ALL = 'REMOVE_LIST_ALL';

export const CHANGE_STATUS_COLLECTION_TO_DO_LIST = 'CHANGE_STATUS_COLLECTION_TO_DO_LIST';

export const SORT_BY_DATA = 'SORT_BY_DATA';

export const SORT_BY_ALPHABET = 'SORT_BY_ALPHABET';

export const CREATE_AUTHORIZED_USER = 'CREATE_AUTHORIZED_USER';

export const VIEW_MESSAGE_AUTH = 'VIEW_MESSAGE_AUTH';

export const SHOW_LOADER = 'SHOW_LOADER';

export const HIDE_LOADER = 'HIDE_LOADER';

export const READE_INITIAL_STATE = 'READE_INITIAL_STATE';
