export const CREATE_COLLECTION_TO_DO = 'CREATE_COLLECTION_TO_DO';

export const CREATE_TO_DO_LIST = 'CREATE_TO_DO_LIST';

export const CHANGE_COMPLETE_STATE = 'CHANGE_COMPLETE_STATE';

export const MAKE_COLLECTION_TO_DO_ACTIVE = 'MAKE_COLLECTION_TO_DO_ACTIVE';

export const SHOW_MODAL_SUCCESSFUL_OPERATION = 'SHOW_MODAL_SUCCESSFUL_OPERATION';

export const HIDE_MODAL_SUCCESSFUL_OPERATION = 'HIDE_MODAL_SUCCESSFUL_OPERATION';

// export const SHOW_MODAL_SUCCESSFUL_OPERATION_LEFT_LIST = 'SHOW_MODAL_SUCCESSFUL_OPERATION_LEFT_LIST';

// export const SHOW_MODAL_SUCCESSFUL_OPERATION_RIGHT_LIST = 'SHOW_MODAL_SUCCESSFUL_OPERATION_RIGHT_LIST';

export const SHOW_MODAL_REMOVE_LIST_ITEM = 'SHOW_MODAL_REMOVE_LIST_ITEM';

export const HIDE_MODAL_REMOVE_LIST_ITEM = 'HIDE_MODAL_REMOVE_LIST_ITEM';

export const REMOVE_LIST_ITEM = 'REMOVE_LIST_ITEM';

export const REMOVE_LIST = 'REMOVE_LIST';

export const REMOVE_LIST_ALL = 'REMOVE_LIST_ALL';

export const CHANGE_STATUS_COLLECTION_TO_DO_LIST = 'CHANGE_STATUS_COLLECTION_TO_DO_LIST';